trigger:
  tags:
    exclude:
      - "v*"
      - "dev/*"
  branches:
    include:
      - "dev"
      - "master"

pool: vmssagentpool

pr:
  branches:
    include:
      - "dev"
      - "master"

resources:
  repositories:
    - repository: templates
      type: github
      name: chaseappio/devops-ci-templates
      ref: refs/heads/master
      endpoint: chaseappio

variables:
  - template: vars.yml@templates
  - name: sdk_version
    value: 3.1.x
  - name: sln_path
    value: mixer-cuckoo.sln

stages:
  - stage: prepare
    jobs:
      - job: version
        steps:
          - template: version.yml@templates

  - stage: build
    condition: "succeeded()"
    jobs:
      - job: build
        steps:
          - template: build.yml@templates
            parameters:
              sdk_version: $(sdk_version)
              sln_path: $(sln_path)
          - template: pack.steps.yml@templates
            parameters:
              sln_path: $(sln_path)
              condition: "and(succeeded(),eq(variables['publish_build'],'true'))"

  - stage: finish
    condition: "and(succeeded(),eq(variables['publish_build'],'true'))"
    jobs:
      - job: github_release
        steps:
          - template: github_release.yml@templates
